#!/usr/bin/perl

$inf=$ARGV[0];

open(IN,"<$inf");
binmode(IN);
$got = read(IN,$line,1000);
$keysize=length($line);
@bytes=unpack("C*",$line);
printf STDERR "BYTES has %d characters\n",$#bytes;

for($ac=0,$i=0;$i<$keysize;$i++){
  # $ac += ($i & 1) ? (ord(substr($line,$i,1))) : (ord(substr($line,$i,1)) << 8);
  $ac += ($i & 1) ? $bytes[$line] : ($bytes[$line] << 8);
  }

printf STDERR "AC is %d\n",$ac;
printf STDERR "AC >> 16 is %d\n",$ac>>16;
$ac += (($ac >> 16) & 0xffff);
printf "%d\n",($ac & 0xffff);

close(IN);

##        for ( ac = 0, i = 0; i < keysize; ++i )
##                   ac += (i & 1) ? key[i] : key[i] << 8;
##           ac += (ac >> 16) & 0xFFFF;
##           return ac & 0xFFFF;
##
